# Copyright (C) 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html
#*******************************************************************************
#* Copyright (C) 2009-2016, International Business Machines Corporation and    *
#* others. All Rights Reserved.                                                *
#*******************************************************************************
api.report.version = 123
api.report.prev.version = 72
release.file.ver = 123_4
api.doc.version = 123.4
maven.pom.ver = 123.4

