# Azure Pipelines (VSTS) configuration for CI builds for ICU.

jobs:

#-------------------------------------------------------------------------
# VS 2019 Builds
#-------------------------------------------------------------------------
- job: ICU4C_Samples_MSVC_x64_Debug
  displayName: 'C: Test Samples MSVC 64-bit Debug (VS 2022)'
  timeoutInMinutes: 30
  pool:
    vmImage: 'windows-2022'
    demands: 
      - msbuild
      - visualstudio
      - Cmd
  steps:
    - checkout: self
      lfs: true
      fetchDepth: 10
    - task: VSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: icu4c/source/allinone/allinone.sln
        platform: x64
        configuration: Debug
    - task: BatchScript@1
      displayName: 'Run Tests (icucheck.bat)'
      inputs:
        filename: icu4c/source/allinone/icucheck.bat
        arguments: 'x64 Debug'
    - task: VSBuild@2
      displayName: 'Build Solution'
      inputs:
        solution: icu4c/source/samples/all/all.sln
        platform: x64
        configuration: Debug
    - task: BatchScript@2
      displayName: 'Test Samples (samplecheck.bat)'
      inputs:
        filename: icu4c/source/samples/all/samplecheck.bat
        arguments: 'x64 Debug'
#-------------------------------------------------------------------------