name: Exhaustive Tests for ICU

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  checks: write
  pull-requests: write

jobs:
  icu4j-linux:
    if: |
      github.event.issue.pull_request != null &&
      (contains(github.event_name, 'workflow_dispatch') ||
      contains(github.event.comment.body, 'run exhaustive tests'))
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Print some debug info
        run: |
          echo "PR: ${{ github.event.issue.pull_request.number }}"
          echo "SHA: ${{ github.event.issue.pull_request.head.sha }}"
          echo "REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}"
      - name: Add a check to the PR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/check-runs
            -f name='Exhaustive Tests Check' \
            -f head_sha="${{ github.event.issue.pull_request.head.sha }}" \
            -f status='in_progress' \

      - name: Build and Exhaustive Tests
        run: |
          echo "Building ICU4J" && cd icu4j && mvn install -DICU.exhaustive=10
        env:
          BUILD: ICU4J

      - name: List failures (if any)
        if: failure()
        run: |
          cd icu4j && cat `find . -name surefire-reports -type d -exec grep -l  -r --include="*.txt" FAILED {} \;`
        timeout-minutes: 2

      - name: Complete the check
        if: always()
        run: |
          STATUS="completed"
          CONCLUSION="success"
          if [ "${{ job.status }}" != "success" ]; then
            CONCLUSION="failure"
          fi
          gh api \
            -X PATCH \
            -F status="$STATUS" \
            -F conclusion="$CONCLUSION" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/check-runs/${{ steps.add_check.outputs.id }}


  icu4c-linux:
    if: contains(github.event_name, 'workflow_dispatch') || contains(github.event.comment.body, 'run exhaustive tests')
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build
        run: |
          cd icu4c/source && ./runConfigureICU Linux/clang && make -j -l4.5
      - name: Exhaustive Tests
        run: |
          cd icu4c/source && make check-exhaustive
        env:
          CC: clang
          CXX: clang++